server.port=9090
fastapi.url=${FASTAPI_URL:http://localhost:8000}
spring.application.name=bfsi-gateway
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
logging.level.com.bfsi=INFO
